new Version of TinyMCE
celements/celements-RTE pull request #5
Opened 2018-05-22 12:35 UTC by dkhasham

https://synjira.atlassian.net/browse/CELDEV-679

2018-05-22 12:35 UTC, dkhasham commented
WorkingTree has now 2 projects:
- TinyMCEv3
- TinyMCEv4

2018-05-23 21:16 UTC, fpichler submitted a review, later dismissed

2018-05-29 09:35 UTC, msladek requested changes
files not correctly moved

2018-05-29 13:11 UTC, msladek approved these changes

2018-07-18 14:54 UTC, merged